name: plugpag
description: Integre o Flutter com maquinas smarts da Pagseguro, utilizando o SDK do Pagseguro. Rápido e fácil.
version: 1.2.0

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.dataclick.plugpag
        pluginClass: PagseguroSmartFlutterPlugin
      ios:
        pluginClass: PagseguroSmartFlutterPlugin
